### ISSUE TITLE
SyntaxError: Non-ASCII character '\xe3' in file

### ISSUE THREAD

**Issue by complyxm** [complyxm/complyxm_gcp#2]
```
Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/941d77da994078b1/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/941d77da994078b1/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 311, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/941d77da994078b1/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 85, in LoadObject
    obj = __import__(path[0])
  File "/base/data/home/apps/b~complyxm-244611/20190727t120641.419885885943192844/main.py", line 4
SyntaxError: Non-ASCII character '\xe3' in file /base/data/home/apps/b~complyxm-244611/20190727t120641.419885885943192844/main.py on line 4, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

I should add
```
# coding: UTF-8
```

**Comment by complyxm** [comment]
Solved
