### ISSUE TITLE
ImportError: No module named requests

### ISSUE THREAD

**Issue by complyxm** [complyxm/complyxm_gcp#4]
```
Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/941d77da994078b1/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/941d77da994078b1/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 311, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/941d77da994078b1/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 85, in LoadObject
    obj = __import__(path[0])
  File "/base/data/home/apps/b~complyxm-244611/20190727t155428.419889554475595548/main.py", line 3, in <module>
    import complyxmmain
  File "/base/data/home/apps/b~complyxm-244611/20190727t155428.419889554475595548/complyxmmain.py", line 2, in <module>
    import requests
ImportError: No module named requests
```

**Comment by complyxm** [comment]
Try https://cloud.google.com/appengine/docs/standard/python/issue-requests?hl=ja

```
import requests
import requests_toolbelt.adapters.appengine

# Use the App Engine Requests adapter. This makes sure that Requests uses
# URLFetch.
requests_toolbelt.adapters.appengine.monkeypatch()
```

**Comment by complyxm** [comment]
After updating requirement.txt, I should run this code and update `lib` folder.
```
pip install -t lib -r requirements.txt
```
