### ISSUE TITLE
ImportError: cannot import name types

### ISSUE THREAD

**Issue by complyxm** [complyxm/complyxm_gcp#7]
```
Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/941d77da994078b1/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/941d77da994078b1/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 311, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/941d77da994078b1/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 85, in LoadObject
    obj = __import__(path[0])
  File "/base/data/home/apps/b~complyxm-244611/20190811t235851.420245271459847911/main.py", line 3, in <module>
    import complyxmmain
  File "/base/data/home/apps/b~complyxm-244611/20190811t235851.420245271459847911/complyxmmain.py", line 27, in <module>
    from google.cloud import firestore
  File "/base/data/home/apps/b~complyxm-244611/20190811t235851.420245271459847911/lib/google/cloud/firestore.py", line 18, in <module>
    from google.cloud.firestore_v1 import __version__
  File "/base/data/home/apps/b~complyxm-244611/20190811t235851.420245271459847911/lib/google/cloud/firestore_v1/__init__.py", line 21, in <module>
    from google.cloud.firestore_v1 import types
ImportError: cannot import name types
```

**Comment by complyxm** [comment]
https://cloud.google.com/datastore/docs/firestore-or-datastore
https://stackoverflow.com/questions/56417857/importerror-cannot-import-name-cygrpc

`App Engine スタンダード環境の Python 2.7 および PHP 5.5 ランタイムではサポートされない`
